// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartReportLog.Persistance;

#nullable disable

namespace SmartReportLog.Migrations
{
    [DbContext(typeof(SmartLogContext))]
    [Migration("20260725100006_AddTicketInfoAndAtmLocation")]
    partial class AddTicketInfoAndAtmLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.Atm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CpuModel")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MInvCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StateCode")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupervisionStateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("StateCode");

                    b.ToTable("Atms");
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmCassetteDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CassetteNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DailyAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Denomination")
                        .HasColumnType("bigint");

                    b.Property<int>("FinalCount")
                        .HasColumnType("int");

                    b.Property<int>("InitialCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalDispense")
                        .HasColumnType("int");

                    b.Property<int>("TotalPickup")
                        .HasColumnType("int");

                    b.Property<int>("TotalReject")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyAnalysisId");

                    b.ToTable("DailyCassettes");
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmDailyAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AuiSeconds")
                        .HasColumnType("float");

                    b.Property<int?>("CpuTemperatureC")
                        .HasColumnType("int");

                    b.Property<int>("CpuUsagePercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyDispenseTotal")
                        .HasColumnType("int");

                    b.Property<int>("DailyRejectTotal")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DiskTotalGb")
                        .HasColumnType("int");

                    b.Property<int>("DiskUsedGb")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("GayaVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonnelCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RamTotalGb")
                        .HasColumnType("int");

                    b.Property<int>("RamUsedGb")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptCount")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalCards")
                        .HasColumnType("int");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtmId", "Date")
                        .IsUnique();

                    b.ToTable("DailyAnalyses");
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmHardwareErrorDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DailyAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DailyAnalysisId", "Device", "ErrorCode");

                    b.ToTable("DailyHardwareErrors");
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmTicketInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CallDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DailyAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReferEndTime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RequestNo")
                        .HasColumnType("int");

                    b.Property<string>("TechName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DailyAnalysisId")
                        .IsUnique();

                    b.HasIndex("RequestNo");

                    b.ToTable("AtmTicketInfos");
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmTodayError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DailyAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DailyAnalysisId", "Date", "Device", "ErrorCode");

                    b.ToTable("AtmTodayErrors");
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.JsonDocuments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("JsonContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("jsonDocuments");
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmCassetteDaily", b =>
                {
                    b.HasOne("SmartReportLog.Entity.AtmAgg.AtmDailyAnalysis", null)
                        .WithMany("Cassettes")
                        .HasForeignKey("DailyAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmDailyAnalysis", b =>
                {
                    b.HasOne("SmartReportLog.Entity.AtmAgg.Atm", null)
                        .WithMany("DailyAnalyses")
                        .HasForeignKey("AtmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmHardwareErrorDaily", b =>
                {
                    b.HasOne("SmartReportLog.Entity.AtmAgg.AtmDailyAnalysis", null)
                        .WithMany("HardwareErrors")
                        .HasForeignKey("DailyAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmTicketInfo", b =>
                {
                    b.HasOne("SmartReportLog.Entity.AtmAgg.AtmDailyAnalysis", null)
                        .WithOne("TicketInfo")
                        .HasForeignKey("SmartReportLog.Entity.AtmAgg.AtmTicketInfo", "DailyAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmTodayError", b =>
                {
                    b.HasOne("SmartReportLog.Entity.AtmAgg.AtmDailyAnalysis", null)
                        .WithMany("TodayErrors")
                        .HasForeignKey("DailyAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.Atm", b =>
                {
                    b.Navigation("DailyAnalyses");
                });

            modelBuilder.Entity("SmartReportLog.Entity.AtmAgg.AtmDailyAnalysis", b =>
                {
                    b.Navigation("Cassettes");

                    b.Navigation("HardwareErrors");

                    b.Navigation("TicketInfo");

                    b.Navigation("TodayErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
